### ISSUE TITLE
Default Value should not be visible in the URL

### ISSUE THREAD

**Issue by unrevised6419** [jeroenpelgrims/vue-use-query-param#17]
I'm not sure if this is a bug, or it was intended to work like this, but it seems when using `withDefault`, the default value is still visible in the URL

For example having a variable `page`, when page is `1` it should not be visible in the URL

Here is an implementation I'm using right now to not show default value in the URL

```ts
export function withDefault<TParam>(
	{ serialize, deserialize }: ParamSerializationConfig<TParam>,
	defaultValue: NonNullable<TParam>,
): ParamSerializationConfig<NonNullable<TParam>> {
	return {
		serialize: (param) => (param === defaultValue ? null : serialize(param)),
		deserialize: (value) => deserialize(value) ?? defaultValue,
	};
}
```

**Comment by Howard-Lam-UnitedVanning** [comment]
It does what it says "Non-nullable query parameters" so the query param always has a value, right?
undefined is also a valid query value so you can't really override with it or there is aliasing between the actual value undefined and the default value.
